//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     SLRC-User
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SLRCUser
{
    /// <summary>
    /// Common Interface for Root Contracts.
    /// </summary>
    public interface IContract
    {
        object UserObject { get; set; }
        void AddDevice(BasicTriListWithSmartObject device);
        void RemoveDevice(BasicTriListWithSmartObject device);

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        event EventHandler<EventArgs> Activity;
    }

    /// <summary>
    /// Root contract giving access to top level project items such as Pages and global Widgets.
    /// </summary>
    public sealed class Contract : IContract, IDisposable
    {
        #region Components

        private ComponentMediator ComponentMediator { get; set; }

        public SLRCUser.PoolAudio.IPoolAudio PoolAudio { get { return (SLRCUser.PoolAudio.IPoolAudio)InternalPoolAudio; } }
        private SLRCUser.PoolAudio.PoolAudio InternalPoolAudio { get; set; }

        public SLRCUser.FieldhouseAudio.IFieldhouseAudio FieldhouseAudio { get { return (SLRCUser.FieldhouseAudio.IFieldhouseAudio)InternalFieldhouseAudio; } }
        private SLRCUser.FieldhouseAudio.FieldhouseAudio InternalFieldhouseAudio { get; set; }

        public SLRCUser.BackgroundMusic.IBackgroundMusic BackgroundMusic { get { return (SLRCUser.BackgroundMusic.IBackgroundMusic)InternalBackgroundMusic; } }
        private SLRCUser.BackgroundMusic.BackgroundMusic InternalBackgroundMusic { get; set; }

        public SLRCUser.Locked.ILocked Locked { get { return (SLRCUser.Locked.ILocked)InternalLocked; } }
        private SLRCUser.Locked.Locked InternalLocked { get; set; }

        public SLRCUser.Main.IMain Main { get { return (SLRCUser.Main.IMain)InternalMain; } }
        private SLRCUser.Main.Main InternalMain { get; set; }

        public SLRCUser.CableTV.ICableTV CableTV { get { return (SLRCUser.CableTV.ICableTV)InternalCableTV; } }
        private SLRCUser.CableTV.CableTV InternalCableTV { get; set; }

        public SLRCUser.PublicDisplays.IPublicDisplays PublicDisplays { get { return (SLRCUser.PublicDisplays.IPublicDisplays)InternalPublicDisplays; } }
        private SLRCUser.PublicDisplays.PublicDisplays InternalPublicDisplays { get; set; }

        public SLRCUser.ISystemInitializing SystemInitializing { get { return (SLRCUser.ISystemInitializing)InternalSystemInitializing; } }
        private SLRCUser.SystemInitializing InternalSystemInitializing { get; set; }

        #endregion

        #region Construction and Initialization

        public Contract()
            : this(new List<BasicTriListWithSmartObject>().ToArray())
        {
        }

        public Contract(BasicTriListWithSmartObject device)
            : this(new [] { device })
        {
        }

        public Contract(BasicTriListWithSmartObject[] devices)
        {
            if (devices == null)
                throw new ArgumentNullException("Devices is null");

            ComponentMediator = new ComponentMediator();
            ComponentMediator.ConfigureActivityEvent(onActivity);

            InternalPoolAudio = new SLRCUser.PoolAudio.PoolAudio(ComponentMediator, 1);

            InternalFieldhouseAudio = new SLRCUser.FieldhouseAudio.FieldhouseAudio(ComponentMediator, 12);

            InternalBackgroundMusic = new SLRCUser.BackgroundMusic.BackgroundMusic(ComponentMediator, 40);

            InternalLocked = new SLRCUser.Locked.Locked(ComponentMediator, 48);

            InternalMain = new SLRCUser.Main.Main(ComponentMediator, 51);

            InternalCableTV = new SLRCUser.CableTV.CableTV(ComponentMediator, 55);

            InternalPublicDisplays = new SLRCUser.PublicDisplays.PublicDisplays(ComponentMediator, 61);

            InternalSystemInitializing = new SLRCUser.SystemInitializing(ComponentMediator, 71);


            for (int index = 0; index < devices.Length; index++)
            {
                AddDevice(devices[index]);
            }
        }

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        public event EventHandler<EventArgs> Activity;
        private void onActivity(GenericBase currentDevice, SmartObjectEventArgs args)
        {
            var handler = Activity;
            if (handler != null)
                handler(currentDevice, args);
        }
        #endregion

        #region Standard Contract Members

        public object UserObject { get; set; }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            InternalPoolAudio.AddDevice(device);
            InternalFieldhouseAudio.AddDevice(device);
            InternalBackgroundMusic.AddDevice(device);
            InternalLocked.AddDevice(device);
            InternalMain.AddDevice(device);
            InternalCableTV.AddDevice(device);
            InternalPublicDisplays.AddDevice(device);
            InternalSystemInitializing.AddDevice(device);

        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            InternalPoolAudio.RemoveDevice(device);
            InternalFieldhouseAudio.RemoveDevice(device);
            InternalBackgroundMusic.RemoveDevice(device);
            InternalLocked.RemoveDevice(device);
            InternalMain.RemoveDevice(device);
            InternalCableTV.RemoveDevice(device);
            InternalPublicDisplays.RemoveDevice(device);
            InternalSystemInitializing.RemoveDevice(device);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            InternalPoolAudio.Dispose();
            InternalFieldhouseAudio.Dispose();
            InternalBackgroundMusic.Dispose();
            InternalLocked.Dispose();
            InternalMain.Dispose();
            InternalCableTV.Dispose();
            InternalPublicDisplays.Dispose();
            InternalSystemInitializing.Dispose();

            ComponentMediator.Dispose(); 
        }

        #endregion
    }
}

