//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     SLRC-Tech
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCTech;

namespace SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList
{

    /// <summary>
    /// FloorboxesOuterWidgetList
    /// </summary>
    public partial interface IFloorboxesOuterWidgetList 
    {
        object UserObject { get; set; }

        /// <summary>
        /// ComplexComponent Fieldhouse-Pool Audio Controls.Items[{0}]s[0]
        /// </summary>
        SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.IItems_0_ Items_0_ { get; }

        /// <summary>
        /// ComplexComponent Fieldhouse-Pool Audio Controls.Items[{0}]s[1]
        /// </summary>
        SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.IItems_1_ Items_1_ { get; }

        /// <summary>
        /// ComplexComponent Fieldhouse-Pool Audio Controls.Items[{0}]s[2]
        /// </summary>
        SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.IItems_2_ Items_2_ { get; }

        /// <summary>
        /// ComplexComponent Fieldhouse-Pool Audio Controls.Items[{0}]s[3]
        /// </summary>
        SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.IItems_3_ Items_3_ { get; }

        /// <summary>
        /// ComplexComponent Fieldhouse-Pool Audio Controls.Items[{0}]s[4]
        /// </summary>
        SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.IItems_4_ Items_4_ { get; }

        /// <summary>
        /// ComplexComponent Fieldhouse-Pool Audio Controls.Items[{0}]
        /// </summary>
        SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.IItem Item { get; }
    }


    /// <summary>
    /// FloorboxesOuterWidgetList
    /// </summary>
    internal partial class FloorboxesOuterWidgetList : IFloorboxesOuterWidgetList, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="FloorboxesOuterWidgetList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal FloorboxesOuterWidgetList(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FloorboxesOuterWidgetList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal FloorboxesOuterWidgetList(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="FloorboxesOuterWidgetList"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            Items_0_ = new SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_0_(ComponentMediator, 70, 5);
            Items_1_ = new SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_1_(ComponentMediator, 71, 5);
            Items_2_ = new SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_2_(ComponentMediator, 72, 5);
            Items_3_ = new SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_3_(ComponentMediator, 73, 5);
            Items_4_ = new SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_4_(ComponentMediator, 74, 5);
            Item = new SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Item(ComponentMediator, 70, 5);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_0_)Items_0_).AddDevice(device);

            ((SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_1_)Items_1_).AddDevice(device);

            ((SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_2_)Items_2_).AddDevice(device);

            ((SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_3_)Items_3_).AddDevice(device);

            ((SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_4_)Items_4_).AddDevice(device);

            ((SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Item)Item).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_0_)Items_0_).RemoveDevice(device);

            ((SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_1_)Items_1_).RemoveDevice(device);

            ((SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_2_)Items_2_).RemoveDevice(device);

            ((SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_3_)Items_3_).RemoveDevice(device);

            ((SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Items_4_)Items_4_).RemoveDevice(device);

            ((SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.Item)Item).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        public SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.IItems_0_ Items_0_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        public SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.IItems_1_ Items_1_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        public SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.IItems_2_ Items_2_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        public SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.IItems_3_ Items_3_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[4]
        /// </summary>
        public SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.IItems_4_ Items_4_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[{0}]
        /// </summary>
        public SLRCTech.FieldhouseAudio.FloorboxesOuterWidgetList.IItem Item { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "FloorboxesOuterWidgetList", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
