//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.701.5.0
//     UI Plugin:   1.4301.17.0
//
//     Project:     SLRC-Classroom
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.1
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SLRCClassroom
{
    /// <summary>
    /// Common Interface for Root Contracts.
    /// </summary>
    public interface IContract
    {
        object UserObject { get; set; }
        void AddDevice(BasicTriListWithSmartObject device);
        void RemoveDevice(BasicTriListWithSmartObject device);

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        event EventHandler<EventArgs> Activity;
    }

    /// <summary>
    /// Root contract giving access to top level project items such as Pages and global Widgets.
    /// </summary>
    public sealed class Contract : IContract, IDisposable
    {
        #region Components

        private ComponentMediator ComponentMediator { get; set; }

        public SLRCClassroom.Tools.ITools Tools { get { return (SLRCClassroom.Tools.ITools)InternalTools; } }
        private SLRCClassroom.Tools.Tools InternalTools { get; set; }

        public SLRCClassroom.IDisplayPowerOffConfirmCom DisplayPowerOffConfirmCom { get { return (SLRCClassroom.IDisplayPowerOffConfirmCom)InternalDisplayPowerOffConfirmCom; } }
        private SLRCClassroom.DisplayPowerOffConfirmCom InternalDisplayPowerOffConfirmCom { get; set; }

        public SLRCClassroom.IDisplayPowerOff DisplayPowerOff { get { return (SLRCClassroom.IDisplayPowerOff)InternalDisplayPowerOff; } }
        private SLRCClassroom.DisplayPowerOff InternalDisplayPowerOff { get; set; }

        public SLRCClassroom.ISystemInitializing SystemInitializing { get { return (SLRCClassroom.ISystemInitializing)InternalSystemInitializing; } }
        private SLRCClassroom.SystemInitializing InternalSystemInitializing { get; set; }

        public SLRCClassroom.Main.IMain Main { get { return (SLRCClassroom.Main.IMain)InternalMain; } }
        private SLRCClassroom.Main.Main InternalMain { get; set; }

        public SLRCClassroom.IDisplayPowerOffConfirmSep DisplayPowerOffConfirmSep { get { return (SLRCClassroom.IDisplayPowerOffConfirmSep)InternalDisplayPowerOffConfirmSep; } }
        private SLRCClassroom.DisplayPowerOffConfirmSep InternalDisplayPowerOffConfirmSep { get; set; }

        public SLRCClassroom.IDisplayPowerOn DisplayPowerOn { get { return (SLRCClassroom.IDisplayPowerOn)InternalDisplayPowerOn; } }
        private SLRCClassroom.DisplayPowerOn InternalDisplayPowerOn { get; set; }

        public SLRCClassroom.ILocked Locked { get { return (SLRCClassroom.ILocked)InternalLocked; } }
        private SLRCClassroom.Locked InternalLocked { get; set; }

        #endregion

        #region Construction and Initialization

        public Contract()
            : this(new List<BasicTriListWithSmartObject>().ToArray())
        {
        }

        public Contract(BasicTriListWithSmartObject device)
            : this(new [] { device })
        {
        }

        public Contract(BasicTriListWithSmartObject[] devices)
        {
            if (devices == null)
                throw new ArgumentNullException("Devices is null");

            ComponentMediator = new ComponentMediator();
            ComponentMediator.ConfigureActivityEvent(onActivity);

            InternalTools = new SLRCClassroom.Tools.Tools(ComponentMediator, 1);

            InternalDisplayPowerOffConfirmCom = new SLRCClassroom.DisplayPowerOffConfirmCom(ComponentMediator, 4);

            InternalDisplayPowerOff = new SLRCClassroom.DisplayPowerOff(ComponentMediator, 5);

            InternalSystemInitializing = new SLRCClassroom.SystemInitializing(ComponentMediator, 6);

            InternalMain = new SLRCClassroom.Main.Main(ComponentMediator, 7);

            InternalDisplayPowerOffConfirmSep = new SLRCClassroom.DisplayPowerOffConfirmSep(ComponentMediator, 9);

            InternalDisplayPowerOn = new SLRCClassroom.DisplayPowerOn(ComponentMediator, 10);

            InternalLocked = new SLRCClassroom.Locked(ComponentMediator, 11);


            for (int index = 0; index < devices.Length; index++)
            {
                AddDevice(devices[index]);
            }
        }

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        public event EventHandler<EventArgs> Activity;
        private void onActivity(GenericBase currentDevice, SmartObjectEventArgs args)
        {
            var handler = Activity;
            if (handler != null)
                handler(currentDevice, args);
        }
        #endregion

        #region Standard Contract Members

        public object UserObject { get; set; }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            InternalTools.AddDevice(device);
            InternalDisplayPowerOffConfirmCom.AddDevice(device);
            InternalDisplayPowerOff.AddDevice(device);
            InternalSystemInitializing.AddDevice(device);
            InternalMain.AddDevice(device);
            InternalDisplayPowerOffConfirmSep.AddDevice(device);
            InternalDisplayPowerOn.AddDevice(device);
            InternalLocked.AddDevice(device);

        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            InternalTools.RemoveDevice(device);
            InternalDisplayPowerOffConfirmCom.RemoveDevice(device);
            InternalDisplayPowerOff.RemoveDevice(device);
            InternalSystemInitializing.RemoveDevice(device);
            InternalMain.RemoveDevice(device);
            InternalDisplayPowerOffConfirmSep.RemoveDevice(device);
            InternalDisplayPowerOn.RemoveDevice(device);
            InternalLocked.RemoveDevice(device);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            InternalTools.Dispose();
            InternalDisplayPowerOffConfirmCom.Dispose();
            InternalDisplayPowerOff.Dispose();
            InternalSystemInitializing.Dispose();
            InternalMain.Dispose();
            InternalDisplayPowerOffConfirmSep.Dispose();
            InternalDisplayPowerOn.Dispose();
            InternalLocked.Dispose();

            ComponentMediator.Dispose(); 
        }

        #endregion
    }
}

