//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     SLRC-Classroom
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCClassroom;

namespace SLRCClassroom
{

    /// <summary>
    /// Display Power Off
    /// </summary>
    public partial interface IDisplayPowerOff 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Display Power Off.VisibilityJoin Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DisplayPowerOff_VisibilityJoin(DisplayPowerOffBoolInputSigDelegate callback);

        /// <summary>
        /// Display Power Off.VisibilityJoin Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DisplayPowerOff_VisibilityJoin(bool digital);

        /// <summary>
        /// Display Off Gauge.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void DisplayOffGauge_LowerTouchfb(DisplayPowerOffUShortInputSigDelegate callback);

        /// <summary>
        /// Display Off Gauge.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void DisplayOffGauge_LowerTouchfb(ushort analog);

        /// <summary>
        /// Display Off Gauge.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void DisplayOffGauge_LowerTouchfb(short analog);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="displaypoweroff">The <see cref="IDisplayPowerOff"/> on which to apply the feedback.</param>
    public delegate void DisplayPowerOffBoolInputSigDelegate(BoolInputSig boolInputSig, IDisplayPowerOff displaypoweroff);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="displaypoweroff">The <see cref="IDisplayPowerOff"/> on which to apply the feedback.</param>
    public delegate void DisplayPowerOffUShortInputSigDelegate(UShortInputSig uShortInputSig, IDisplayPowerOff displaypoweroff);

    /// <summary>
    /// Display Power Off
    /// </summary>
    internal partial class DisplayPowerOff : IDisplayPowerOff, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: DisplayPowerOffVisibilityJoin
                /// Display Power Off.VisibilityJoin
                /// </summary>
                public const uint DisplayPowerOff_VisibilityJoinState = 1;

            }
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: DisplayPowerOff.DisplayOffGauge.LowerTouchfb
                /// Display Off Gauge.Lower Touch fb
                /// </summary>
                public const uint DisplayOffGauge_LowerTouchfbState = 4;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="DisplayPowerOff"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal DisplayPowerOff(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DisplayPowerOff"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal DisplayPowerOff(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="DisplayPowerOff"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public void DisplayPowerOff_VisibilityJoin(DisplayPowerOffBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DisplayPowerOff_VisibilityJoinState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayPowerOff_VisibilityJoin(bool digital)
        {
            DisplayPowerOff_VisibilityJoin((sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void DisplayOffGauge_LowerTouchfb(DisplayPowerOffUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.DisplayOffGauge_LowerTouchfbState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayOffGauge_LowerTouchfb(ushort analog)
        {
            DisplayOffGauge_LowerTouchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void DisplayOffGauge_LowerTouchfb(short analog)
        {
            DisplayOffGauge_LowerTouchfb((sig, component) => sig.ShortValue = analog);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "DisplayPowerOff", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
