//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     SLRC-Tech
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCTech;

namespace SLRCTech.Classrooms
{

    /// <summary>
    /// Classrooms
    /// </summary>
    public partial interface IClassrooms 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Classrooms.VisibilityJoin Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Classrooms_VisibilityJoin(ClassroomsBoolInputSigDelegate callback);

        /// <summary>
        /// Classrooms.VisibilityJoin Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Classrooms_VisibilityJoin(bool digital);

        /// <summary>
        /// ComplexComponent Header
        /// </summary>
        SLRCTech.Classrooms.IHeader Header { get; }

        /// <summary>
        /// ComplexComponent Building Mute
        /// </summary>
        SLRCTech.Classrooms.IBuildingMute BuildingMute { get; }

        /// <summary>
        /// ComplexComponent Classroom Controls
        /// </summary>
        SLRCTech.Classrooms.ThirdFloorClassroom.IThirdFloorClassroom ThirdFloorClassroom { get; }

        /// <summary>
        /// ComplexComponent Classroom Controls
        /// </summary>
        SLRCTech.Classrooms.SecondFloorClassroom.ISecondFloorClassroom SecondFloorClassroom { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="classrooms">The <see cref="IClassrooms"/> on which to apply the feedback.</param>
    public delegate void ClassroomsBoolInputSigDelegate(BoolInputSig boolInputSig, IClassrooms classrooms);

    /// <summary>
    /// Classrooms
    /// </summary>
    internal partial class Classrooms : IClassrooms, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ClassroomsVisibilityJoin
                /// Classrooms.VisibilityJoin
                /// </summary>
                public const uint Classrooms_VisibilityJoinState = 1;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="Classrooms"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal Classrooms(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Classrooms"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal Classrooms(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="Classrooms"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            Header = new SLRCTech.Classrooms.Header(ComponentMediator, 22);
            BuildingMute = new SLRCTech.Classrooms.BuildingMute(ComponentMediator, 24);
            ThirdFloorClassroom = new SLRCTech.Classrooms.ThirdFloorClassroom.ThirdFloorClassroom(ComponentMediator, 25);
            SecondFloorClassroom = new SLRCTech.Classrooms.SecondFloorClassroom.SecondFloorClassroom(ComponentMediator, 31);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCTech.Classrooms.Header)Header).AddDevice(device);

            ((SLRCTech.Classrooms.BuildingMute)BuildingMute).AddDevice(device);

            ((SLRCTech.Classrooms.ThirdFloorClassroom.ThirdFloorClassroom)ThirdFloorClassroom).AddDevice(device);

            ((SLRCTech.Classrooms.SecondFloorClassroom.SecondFloorClassroom)SecondFloorClassroom).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCTech.Classrooms.Header)Header).RemoveDevice(device);

            ((SLRCTech.Classrooms.BuildingMute)BuildingMute).RemoveDevice(device);

            ((SLRCTech.Classrooms.ThirdFloorClassroom.ThirdFloorClassroom)ThirdFloorClassroom).RemoveDevice(device);

            ((SLRCTech.Classrooms.SecondFloorClassroom.SecondFloorClassroom)SecondFloorClassroom).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public void Classrooms_VisibilityJoin(ClassroomsBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Classrooms_VisibilityJoinState], this);
            }
        }

        /// <inheritdoc/>
        public void Classrooms_VisibilityJoin(bool digital)
        {
            Classrooms_VisibilityJoin((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent Header
        /// </summary>
        public SLRCTech.Classrooms.IHeader Header { get; private set; }

        /// <summary>
        /// ComplexComponent BuildingMute
        /// </summary>
        public SLRCTech.Classrooms.IBuildingMute BuildingMute { get; private set; }

        /// <summary>
        /// ComplexComponent ThirdFloorClassroom
        /// </summary>
        public SLRCTech.Classrooms.ThirdFloorClassroom.IThirdFloorClassroom ThirdFloorClassroom { get; private set; }

        /// <summary>
        /// ComplexComponent SecondFloorClassroom
        /// </summary>
        public SLRCTech.Classrooms.SecondFloorClassroom.ISecondFloorClassroom SecondFloorClassroom { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "Classrooms", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
