//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     SLRC-Tech
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCTech;

namespace SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList
{

    /// <summary>
    /// Items[4]
    /// </summary>
    public partial interface IItems_4_ 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 1 Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> DisplayHDMI1Button_PressEvent;

        /// <summary>
        /// Event PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 2 Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> DisplayHDMI2Button_PressEvent;

        /// <summary>
        /// Event PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Off Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> DisplayOffButton_PressEvent;

        /// <summary>
        /// Event PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display On Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> DisplayOnButton_PressEvent;

        /// <summary>
        /// Event PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Down Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> DisplayVolumeDownButton_PressEvent;

        /// <summary>
        /// Event PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Up Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> DisplayVolumeUpButton_PressEvent;

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 1 Button.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DisplayHDMI1Button_Visibility_fb(Items_4_BoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 1 Button.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DisplayHDMI1Button_Visibility_fb(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 2 Button.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DisplayHDMI2Button_Visibility_fb(Items_4_BoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 2 Button.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DisplayHDMI2Button_Visibility_fb(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Down Button.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DisplayVolumeDownButton_Visibility_fb(Items_4_BoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Down Button.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DisplayVolumeDownButton_Visibility_fb(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Gauge.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DisplayVolumeGauge_Visibility_fb(Items_4_BoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Gauge.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DisplayVolumeGauge_Visibility_fb(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Up Button.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DisplayVolumeUpButton_Visibility_fb(Items_4_BoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Up Button.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DisplayVolumeUpButton_Visibility_fb(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 1 Button.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DisplayHDMI1Button_Selected(Items_4_BoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 1 Button.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DisplayHDMI1Button_Selected(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 2 Button.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DisplayHDMI2Button_Selected(Items_4_BoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 2 Button.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DisplayHDMI2Button_Selected(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Off Button.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DisplayOffButton_Selected(Items_4_BoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Off Button.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DisplayOffButton_Selected(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display On Button.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void DisplayOnButton_Selected(Items_4_BoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display On Button.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void DisplayOnButton_Selected(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Gauge.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void DisplayVolumeGauge_LowerTouchfb(Items_4_UShortInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Gauge.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void DisplayVolumeGauge_LowerTouchfb(ushort analog);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Gauge.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void DisplayVolumeGauge_LowerTouchfb(short analog);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Label.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void DisplayLabel_IndirectRichText(Items_4_StringInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Label.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void DisplayLabel_IndirectRichText(string serial);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="items_4_">The <see cref="IItems_4_"/> on which to apply the feedback.</param>
    public delegate void Items_4_BoolInputSigDelegate(BoolInputSig boolInputSig, IItems_4_ items_4_);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="items_4_">The <see cref="IItems_4_"/> on which to apply the feedback.</param>
    public delegate void Items_4_UShortInputSigDelegate(UShortInputSig uShortInputSig, IItems_4_ items_4_);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="items_4_">The <see cref="IItems_4_"/> on which to apply the feedback.</param>
    public delegate void Items_4_StringInputSigDelegate(StringInputSig stringInputSig, IItems_4_ items_4_);

    /// <summary>
    /// Items[4]
    /// </summary>
    internal partial class Items_4_ : IItems_4_, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayHDMI1Button.Press
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 1 Button.Press
                /// </summary>
                public const uint DisplayHDMI1Button_PressEvent = 601;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayHDMI2Button.Press
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 2 Button.Press
                /// </summary>
                public const uint DisplayHDMI2Button_PressEvent = 602;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayOffButton.Press
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Off Button.Press
                /// </summary>
                public const uint DisplayOffButton_PressEvent = 603;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayOnButton.Press
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display On Button.Press
                /// </summary>
                public const uint DisplayOnButton_PressEvent = 604;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayVolumeDownButton.Press
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Down Button.Press
                /// </summary>
                public const uint DisplayVolumeDownButton_PressEvent = 605;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayVolumeUpButton.Press
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Up Button.Press
                /// </summary>
                public const uint DisplayVolumeUpButton_PressEvent = 606;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayHDMI1Button.Visibility_fb
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 1 Button.Visibility
                /// </summary>
                public const uint DisplayHDMI1Button_Visibility_fbState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayHDMI2Button.Visibility_fb
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 2 Button.Visibility
                /// </summary>
                public const uint DisplayHDMI2Button_Visibility_fbState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayVolumeDownButton.Visibility_fb
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Down Button.Visibility
                /// </summary>
                public const uint DisplayVolumeDownButton_Visibility_fbState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayVolumeGauge.Visibility_fb
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Gauge.Visibility
                /// </summary>
                public const uint DisplayVolumeGauge_Visibility_fbState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayVolumeUpButton.Visibility_fb
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Up Button.Visibility
                /// </summary>
                public const uint DisplayVolumeUpButton_Visibility_fbState = 5;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayHDMI1Button.Selected
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 1 Button.Selected
                /// </summary>
                public const uint DisplayHDMI1Button_SelectedState = 606;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayHDMI2Button.Selected
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display HDMI 2 Button.Selected
                /// </summary>
                public const uint DisplayHDMI2Button_SelectedState = 607;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayOffButton.Selected
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Off Button.Selected
                /// </summary>
                public const uint DisplayOffButton_SelectedState = 608;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayOnButton.Selected
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display On Button.Selected
                /// </summary>
                public const uint DisplayOnButton_SelectedState = 609;

            }
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayVolumeGauge.LowerTouchfb
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Volume Gauge.Lower Touch fb
                /// </summary>
                public const uint DisplayVolumeGauge_LowerTouchfbState = 1801;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].DisplayControlsCONTRACT.DisplayLabel.IndirectRichText
                /// PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items[4].Display Label.Indirect Rich Text
                /// </summary>
                public const uint DisplayLabel_IndirectRichTextState = 1;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_4_"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal Items_4_(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_4_"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal Items_4_(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_4_"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.DisplayHDMI1Button_PressEvent, onDisplayHDMI1Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.DisplayHDMI2Button_PressEvent, onDisplayHDMI2Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.DisplayOffButton_PressEvent, onDisplayOffButton_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.DisplayOnButton_PressEvent, onDisplayOnButton_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.DisplayVolumeDownButton_PressEvent, onDisplayVolumeDownButton_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.DisplayVolumeUpButton_PressEvent, onDisplayVolumeUpButton_Press);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            return new Indexes((ushort)(controlJoinId - ControlJoinId), 0, false);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> DisplayHDMI1Button_PressEvent;
        private void onDisplayHDMI1Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = DisplayHDMI1Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> DisplayHDMI2Button_PressEvent;
        private void onDisplayHDMI2Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = DisplayHDMI2Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> DisplayOffButton_PressEvent;
        private void onDisplayOffButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = DisplayOffButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> DisplayOnButton_PressEvent;
        private void onDisplayOnButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = DisplayOnButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> DisplayVolumeDownButton_PressEvent;
        private void onDisplayVolumeDownButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = DisplayVolumeDownButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> DisplayVolumeUpButton_PressEvent;
        private void onDisplayVolumeUpButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = DisplayVolumeUpButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void DisplayHDMI1Button_Selected(Items_4_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DisplayHDMI1Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayHDMI1Button_Selected(bool digital)
        {
            DisplayHDMI1Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DisplayHDMI1Button_Visibility_fb(Items_4_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DisplayHDMI1Button_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayHDMI1Button_Visibility_fb(bool digital)
        {
            DisplayHDMI1Button_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DisplayHDMI2Button_Selected(Items_4_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DisplayHDMI2Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayHDMI2Button_Selected(bool digital)
        {
            DisplayHDMI2Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DisplayHDMI2Button_Visibility_fb(Items_4_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DisplayHDMI2Button_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayHDMI2Button_Visibility_fb(bool digital)
        {
            DisplayHDMI2Button_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DisplayOffButton_Selected(Items_4_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DisplayOffButton_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayOffButton_Selected(bool digital)
        {
            DisplayOffButton_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DisplayOnButton_Selected(Items_4_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DisplayOnButton_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayOnButton_Selected(bool digital)
        {
            DisplayOnButton_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DisplayVolumeDownButton_Visibility_fb(Items_4_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DisplayVolumeDownButton_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayVolumeDownButton_Visibility_fb(bool digital)
        {
            DisplayVolumeDownButton_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DisplayVolumeGauge_Visibility_fb(Items_4_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DisplayVolumeGauge_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayVolumeGauge_Visibility_fb(bool digital)
        {
            DisplayVolumeGauge_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void DisplayVolumeUpButton_Visibility_fb(Items_4_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.DisplayVolumeUpButton_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayVolumeUpButton_Visibility_fb(bool digital)
        {
            DisplayVolumeUpButton_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void DisplayVolumeGauge_LowerTouchfb(Items_4_UShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.DisplayVolumeGauge_LowerTouchfbState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayVolumeGauge_LowerTouchfb(ushort analog)
        {
            DisplayVolumeGauge_LowerTouchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void DisplayVolumeGauge_LowerTouchfb(short analog)
        {
            DisplayVolumeGauge_LowerTouchfb((sig, component) => sig.ShortValue = analog);
        }

        /// <inheritdoc/>
        public void DisplayLabel_IndirectRichText(Items_4_StringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.DisplayLabel_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void DisplayLabel_IndirectRichText(string serial)
        {
            DisplayLabel_IndirectRichText((sig, component) => sig.StringValue = serial);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "Items_4_", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            DisplayHDMI1Button_PressEvent = null;
            DisplayHDMI2Button_PressEvent = null;
            DisplayOffButton_PressEvent = null;
            DisplayOnButton_PressEvent = null;
            DisplayVolumeDownButton_PressEvent = null;
            DisplayVolumeUpButton_PressEvent = null;
        }

        #endregion
    }
}
