//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     SLRC-Tech
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCTech;

namespace SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface ILoWidgetListByItem
    {

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Visible(ushort listItemIndex, LoWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// Helper PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Visible(ushort listItemIndex, bool digital);
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class LoWidgetList
    {
        #region CH5 Contract
        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, LoWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.LoWidgetList_List_Item1_VisibleState + (uint) listItemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, bool digital)
        {
            List_Item_Visible(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }


        #endregion
    }

    /// <summary>
    /// LoWidgetList
    /// </summary>
    public partial interface ILoWidgetList : ILoWidgetListByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void LoWidgetList_List_Visible(LoWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void LoWidgetList_List_Visible(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void LoWidgetList_List_Item1_Visible(LoWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void LoWidgetList_List_Item1_Visible(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void LoWidgetList_List_Item2_Visible(LoWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void LoWidgetList_List_Item2_Visible(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void LoWidgetList_List_Item3_Visible(LoWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void LoWidgetList_List_Item3_Visible(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void LoWidgetList_List_Item4_Visible(LoWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void LoWidgetList_List_Item4_Visible(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void LoWidgetList_List_Item5_Visible(LoWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void LoWidgetList_List_Item5_Visible(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void LoWidgetList_List_Item6_Visible(LoWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void LoWidgetList_List_Item6_Visible(bool digital);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List Number Of Items Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void LoWidgetList_Set_Number_Of_Items(LoWidgetListUShortInputSigDelegate callback);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List Number Of Items Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void LoWidgetList_Set_Number_Of_Items(ushort analog);

        /// <summary>
        /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List Number Of Items Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void LoWidgetList_Set_Number_Of_Items(short analog);

        /// <summary>
        /// ComplexComponent Display Controls.Items[{0}]s[0]
        /// </summary>
        SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItems_0_ Items_0_ { get; }

        /// <summary>
        /// ComplexComponent Display Controls.Items[{0}]s[1]
        /// </summary>
        SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItems_1_ Items_1_ { get; }

        /// <summary>
        /// ComplexComponent Display Controls.Items[{0}]s[2]
        /// </summary>
        SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItems_2_ Items_2_ { get; }

        /// <summary>
        /// ComplexComponent Display Controls.Items[{0}]s[3]
        /// </summary>
        SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItems_3_ Items_3_ { get; }

        /// <summary>
        /// ComplexComponent Display Controls.Items[{0}]s[4]
        /// </summary>
        SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItems_4_ Items_4_ { get; }

        /// <summary>
        /// ComplexComponent Display Controls.Items[{0}]s[5]
        /// </summary>
        SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItems_5_ Items_5_ { get; }

        /// <summary>
        /// ComplexComponent Display Controls.Items[{0}]
        /// </summary>
        SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItem Item { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="lowidgetlist">The <see cref="ILoWidgetList"/> on which to apply the feedback.</param>
    public delegate void LoWidgetListBoolInputSigDelegate(BoolInputSig boolInputSig, ILoWidgetList lowidgetlist);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="lowidgetlist">The <see cref="ILoWidgetList"/> on which to apply the feedback.</param>
    public delegate void LoWidgetListUShortInputSigDelegate(UShortInputSig uShortInputSig, ILoWidgetList lowidgetlist);

    /// <summary>
    /// LoWidgetList
    /// </summary>
    internal partial class LoWidgetList : ILoWidgetList, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.List_Visible
                /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List Visibility
                /// </summary>
                public const uint LoWidgetList_List_VisibleState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.List_Item1_Visible
                /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item1_Visible
                /// </summary>
                public const uint LoWidgetList_List_Item1_VisibleState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.List_Item2_Visible
                /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item2_Visible
                /// </summary>
                public const uint LoWidgetList_List_Item2_VisibleState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.List_Item3_Visible
                /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item3_Visible
                /// </summary>
                public const uint LoWidgetList_List_Item3_VisibleState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.List_Item4_Visible
                /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item4_Visible
                /// </summary>
                public const uint LoWidgetList_List_Item4_VisibleState = 5;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.List_Item5_Visible
                /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item5_Visible
                /// </summary>
                public const uint LoWidgetList_List_Item5_VisibleState = 6;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.List_Item6_Visible
                /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List_Item6_Visible
                /// </summary>
                public const uint LoWidgetList_List_Item6_VisibleState = 7;

            }
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {
                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Set_Number_Of_Items
                /// PublicDisplays.PublicDisplay1stFloor.LoWidget List.List Number Of Items
                /// </summary>
                public const uint LoWidgetList_Set_Number_Of_ItemsState = 2;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="LoWidgetList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal LoWidgetList(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoWidgetList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal LoWidgetList(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="LoWidgetList"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            Items_0_ = new SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_0_(ComponentMediator, 106, 6);
            Items_1_ = new SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_1_(ComponentMediator, 107, 6);
            Items_2_ = new SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_2_(ComponentMediator, 108, 6);
            Items_3_ = new SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_3_(ComponentMediator, 109, 6);
            Items_4_ = new SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_4_(ComponentMediator, 110, 6);
            Items_5_ = new SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_5_(ComponentMediator, 111, 6);
            Item = new SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Item(ComponentMediator, 106, 6);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_0_)Items_0_).AddDevice(device);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_1_)Items_1_).AddDevice(device);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_2_)Items_2_).AddDevice(device);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_3_)Items_3_).AddDevice(device);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_4_)Items_4_).AddDevice(device);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_5_)Items_5_).AddDevice(device);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Item)Item).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_0_)Items_0_).RemoveDevice(device);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_1_)Items_1_).RemoveDevice(device);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_2_)Items_2_).RemoveDevice(device);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_3_)Items_3_).RemoveDevice(device);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_4_)Items_4_).RemoveDevice(device);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Items_5_)Items_5_).RemoveDevice(device);

            ((SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.Item)Item).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public void LoWidgetList_List_Item1_Visible(LoWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.LoWidgetList_List_Item1_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void LoWidgetList_List_Item1_Visible(bool digital)
        {
            LoWidgetList_List_Item1_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void LoWidgetList_List_Item2_Visible(LoWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.LoWidgetList_List_Item2_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void LoWidgetList_List_Item2_Visible(bool digital)
        {
            LoWidgetList_List_Item2_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void LoWidgetList_List_Item3_Visible(LoWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.LoWidgetList_List_Item3_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void LoWidgetList_List_Item3_Visible(bool digital)
        {
            LoWidgetList_List_Item3_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void LoWidgetList_List_Item4_Visible(LoWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.LoWidgetList_List_Item4_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void LoWidgetList_List_Item4_Visible(bool digital)
        {
            LoWidgetList_List_Item4_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void LoWidgetList_List_Item5_Visible(LoWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.LoWidgetList_List_Item5_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void LoWidgetList_List_Item5_Visible(bool digital)
        {
            LoWidgetList_List_Item5_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void LoWidgetList_List_Item6_Visible(LoWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.LoWidgetList_List_Item6_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void LoWidgetList_List_Item6_Visible(bool digital)
        {
            LoWidgetList_List_Item6_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void LoWidgetList_List_Visible(LoWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.LoWidgetList_List_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void LoWidgetList_List_Visible(bool digital)
        {
            LoWidgetList_List_Visible((sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void LoWidgetList_Set_Number_Of_Items(LoWidgetListUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.LoWidgetList_Set_Number_Of_ItemsState], this);
            }
        }

        /// <inheritdoc/>
        public void LoWidgetList_Set_Number_Of_Items(ushort analog)
        {
            LoWidgetList_Set_Number_Of_Items((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void LoWidgetList_Set_Number_Of_Items(short analog)
        {
            LoWidgetList_Set_Number_Of_Items((sig, component) => sig.ShortValue = analog);
        }

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        public SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItems_0_ Items_0_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        public SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItems_1_ Items_1_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        public SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItems_2_ Items_2_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        public SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItems_3_ Items_3_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[4]
        /// </summary>
        public SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItems_4_ Items_4_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[5]
        /// </summary>
        public SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItems_5_ Items_5_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[{0}]
        /// </summary>
        public SLRCTech.PublicDisplays.PublicDisplay1stFloor.LoWidgetList.IItem Item { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "LoWidgetList", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
