//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     SLRC-Tech
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SLRCTech
{
    /// <summary>
    /// Common Interface for Root Contracts.
    /// </summary>
    public interface IContract
    {
        object UserObject { get; set; }
        void AddDevice(BasicTriListWithSmartObject device);
        void RemoveDevice(BasicTriListWithSmartObject device);

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        event EventHandler<EventArgs> Activity;
    }

    /// <summary>
    /// Root contract giving access to top level project items such as Pages and global Widgets.
    /// </summary>
    public sealed class Contract : IContract, IDisposable
    {
        #region Components

        private ComponentMediator ComponentMediator { get; set; }

        public SLRCTech.Locked.ILocked Locked { get { return (SLRCTech.Locked.ILocked)InternalLocked; } }
        private SLRCTech.Locked.Locked InternalLocked { get; set; }

        public SLRCTech.Main.IMain Main { get { return (SLRCTech.Main.IMain)InternalMain; } }
        private SLRCTech.Main.Main InternalMain { get; set; }

        public SLRCTech.PoolAudio.IPoolAudio PoolAudio { get { return (SLRCTech.PoolAudio.IPoolAudio)InternalPoolAudio; } }
        private SLRCTech.PoolAudio.PoolAudio InternalPoolAudio { get; set; }

        public SLRCTech.ISystemInitializing SystemInitializing { get { return (SLRCTech.ISystemInitializing)InternalSystemInitializing; } }
        private SLRCTech.SystemInitializing InternalSystemInitializing { get; set; }

        public SLRCTech.Classrooms.IClassrooms Classrooms { get { return (SLRCTech.Classrooms.IClassrooms)InternalClassrooms; } }
        private SLRCTech.Classrooms.Classrooms InternalClassrooms { get; set; }

        public SLRCTech.BackgroundMusic.IBackgroundMusic BackgroundMusic { get { return (SLRCTech.BackgroundMusic.IBackgroundMusic)InternalBackgroundMusic; } }
        private SLRCTech.BackgroundMusic.BackgroundMusic InternalBackgroundMusic { get; set; }

        public SLRCTech.CableTV.ICableTV CableTV { get { return (SLRCTech.CableTV.ICableTV)InternalCableTV; } }
        private SLRCTech.CableTV.CableTV InternalCableTV { get; set; }

        public SLRCTech.FieldhouseAudio.IFieldhouseAudio FieldhouseAudio { get { return (SLRCTech.FieldhouseAudio.IFieldhouseAudio)InternalFieldhouseAudio; } }
        private SLRCTech.FieldhouseAudio.FieldhouseAudio InternalFieldhouseAudio { get; set; }

        public SLRCTech.PublicDisplays.IPublicDisplays PublicDisplays { get { return (SLRCTech.PublicDisplays.IPublicDisplays)InternalPublicDisplays; } }
        private SLRCTech.PublicDisplays.PublicDisplays InternalPublicDisplays { get; set; }

        public SLRCTech.Settings.ISettings Settings { get { return (SLRCTech.Settings.ISettings)InternalSettings; } }
        private SLRCTech.Settings.Settings InternalSettings { get; set; }

        #endregion

        #region Construction and Initialization

        public Contract()
            : this(new List<BasicTriListWithSmartObject>().ToArray())
        {
        }

        public Contract(BasicTriListWithSmartObject device)
            : this(new [] { device })
        {
        }

        public Contract(BasicTriListWithSmartObject[] devices)
        {
            if (devices == null)
                throw new ArgumentNullException("Devices is null");

            ComponentMediator = new ComponentMediator();
            ComponentMediator.ConfigureActivityEvent(onActivity);

            InternalLocked = new SLRCTech.Locked.Locked(ComponentMediator, 1);

            InternalMain = new SLRCTech.Main.Main(ComponentMediator, 4);

            InternalPoolAudio = new SLRCTech.PoolAudio.PoolAudio(ComponentMediator, 8);

            InternalSystemInitializing = new SLRCTech.SystemInitializing(ComponentMediator, 19);

            InternalClassrooms = new SLRCTech.Classrooms.Classrooms(ComponentMediator, 21);

            InternalBackgroundMusic = new SLRCTech.BackgroundMusic.BackgroundMusic(ComponentMediator, 37);

            InternalCableTV = new SLRCTech.CableTV.CableTV(ComponentMediator, 63);

            InternalFieldhouseAudio = new SLRCTech.FieldhouseAudio.FieldhouseAudio(ComponentMediator, 74);

            InternalPublicDisplays = new SLRCTech.PublicDisplays.PublicDisplays(ComponentMediator, 102);

            InternalSettings = new SLRCTech.Settings.Settings(ComponentMediator, 132);


            for (int index = 0; index < devices.Length; index++)
            {
                AddDevice(devices[index]);
            }
        }

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        public event EventHandler<EventArgs> Activity;
        private void onActivity(GenericBase currentDevice, SmartObjectEventArgs args)
        {
            var handler = Activity;
            if (handler != null)
                handler(currentDevice, args);
        }
        #endregion

        #region Standard Contract Members

        public object UserObject { get; set; }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            InternalLocked.AddDevice(device);
            InternalMain.AddDevice(device);
            InternalPoolAudio.AddDevice(device);
            InternalSystemInitializing.AddDevice(device);
            InternalClassrooms.AddDevice(device);
            InternalBackgroundMusic.AddDevice(device);
            InternalCableTV.AddDevice(device);
            InternalFieldhouseAudio.AddDevice(device);
            InternalPublicDisplays.AddDevice(device);
            InternalSettings.AddDevice(device);

        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            InternalLocked.RemoveDevice(device);
            InternalMain.RemoveDevice(device);
            InternalPoolAudio.RemoveDevice(device);
            InternalSystemInitializing.RemoveDevice(device);
            InternalClassrooms.RemoveDevice(device);
            InternalBackgroundMusic.RemoveDevice(device);
            InternalCableTV.RemoveDevice(device);
            InternalFieldhouseAudio.RemoveDevice(device);
            InternalPublicDisplays.RemoveDevice(device);
            InternalSettings.RemoveDevice(device);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            InternalLocked.Dispose();
            InternalMain.Dispose();
            InternalPoolAudio.Dispose();
            InternalSystemInitializing.Dispose();
            InternalClassrooms.Dispose();
            InternalBackgroundMusic.Dispose();
            InternalCableTV.Dispose();
            InternalFieldhouseAudio.Dispose();
            InternalPublicDisplays.Dispose();
            InternalSettings.Dispose();

            ComponentMediator.Dispose(); 
        }

        #endregion
    }
}

