//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.701.5.0
//     UI Plugin:   1.4301.17.0
//
//     Project:     SLRC-User
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.1
//     Strategy:    PageStrategy
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCUser;

namespace SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels
{

    /// <summary>
    /// Background Music Zone Levels
    /// </summary>
    public partial interface IBackgroundMusicZoneLevels
    {
        object UserObject { get; set; }

        /// <summary>
        /// Background Music Zone Levels.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void BackgroundMusicZoneLevels_Visibility_fb(bool digital);

        /// <summary>
        /// Background Music Zone Levels.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void BackgroundMusicZoneLevels_Visibility_fb(BackgroundMusicZoneLevelsBoolInputSigDelegate callback);

        /// <summary>
        /// ComplexComponent Third Floor Levels
        /// </summary>
        SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.ThirdFloorLevels.IThirdFloorLevels ThirdFloorLevels { get; }

        /// <summary>
        /// ComplexComponent First Floor Levels
        /// </summary>
        SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.IFirstFloorLevels FirstFloorLevels { get; }

        /// <summary>
        /// ComplexComponent Second Floor Levels Widget List
        /// </summary>
        SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.SecondFloorLevelsWidgetList.ISecondFloorLevelsWidgetList SecondFloorLevelsWidgetList { get; }

        /// <summary>
        /// ComplexComponent Lower Level Levels
        /// </summary>
        SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.LowerLevelLevels.ILowerLevelLevels LowerLevelLevels { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="backgroundmusiczonelevels">The <see cref="IBackgroundMusicZoneLevels"/> on which to apply the feedback.</param>
    public delegate void BackgroundMusicZoneLevelsBoolInputSigDelegate(BoolInputSig boolInputSig, IBackgroundMusicZoneLevels backgroundmusiczonelevels);

    /// <summary>
    /// Background Music Zone Levels
    /// </summary>
    internal partial class BackgroundMusicZoneLevels : IBackgroundMusicZoneLevels, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: BackgroundMusic.BackgroundMusicZoneLevels.Visibility_fb
                /// Background Music Zone Levels.Visibility
                /// </summary>
                public const uint BackgroundMusicZoneLevels_Visibility_fbState = 1;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="BackgroundMusicZoneLevels"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal BackgroundMusicZoneLevels(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BackgroundMusicZoneLevels"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal BackgroundMusicZoneLevels(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="BackgroundMusicZoneLevels"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ThirdFloorLevels = new SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.ThirdFloorLevels.ThirdFloorLevels(ComponentMediator, 55);
            FirstFloorLevels = new SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.FirstFloorLevels(ComponentMediator, 59);
            SecondFloorLevelsWidgetList = new SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.SecondFloorLevelsWidgetList.SecondFloorLevelsWidgetList(ComponentMediator, 64);
            LowerLevelLevels = new SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.LowerLevelLevels.LowerLevelLevels(ComponentMediator, 69);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.ThirdFloorLevels.ThirdFloorLevels)ThirdFloorLevels).AddDevice(device);

            ((SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.FirstFloorLevels)FirstFloorLevels).AddDevice(device);

            ((SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.SecondFloorLevelsWidgetList.SecondFloorLevelsWidgetList)SecondFloorLevelsWidgetList).AddDevice(device);

            ((SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.LowerLevelLevels.LowerLevelLevels)LowerLevelLevels).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

        ((SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.ThirdFloorLevels.ThirdFloorLevels)ThirdFloorLevels).RemoveDevice(device);

        ((SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.FirstFloorLevels)FirstFloorLevels).RemoveDevice(device);

        ((SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.SecondFloorLevelsWidgetList.SecondFloorLevelsWidgetList)SecondFloorLevelsWidgetList).RemoveDevice(device);

        ((SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.LowerLevelLevels.LowerLevelLevels)LowerLevelLevels).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract
        /// <inheritdoc/>
        public void BackgroundMusicZoneLevels_Visibility_fb(BackgroundMusicZoneLevelsBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.BackgroundMusicZoneLevels_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void BackgroundMusicZoneLevels_Visibility_fb(bool digital)
        {
            BackgroundMusicZoneLevels_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent Third Floor Levels
        /// </summary>
        public SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.ThirdFloorLevels.IThirdFloorLevels ThirdFloorLevels { get; private set; }

        /// <summary>
        /// ComplexComponent First Floor Levels
        /// </summary>
        public SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.IFirstFloorLevels FirstFloorLevels { get; private set; }

        /// <summary>
        /// ComplexComponent Second Floor Levels Widget List
        /// </summary>
        public SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.SecondFloorLevelsWidgetList.ISecondFloorLevelsWidgetList SecondFloorLevelsWidgetList { get; private set; }

        /// <summary>
        /// ComplexComponent Lower Level Levels
        /// </summary>
        public SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels.LowerLevelLevels.ILowerLevelLevels LowerLevelLevels { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "BackgroundMusicZoneLevels", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
