//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.701.5.0
//     UI Plugin:   1.4301.17.0
//
//     Project:     SLRC-Tech
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.1
//     Strategy:    PageStrategy
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCTech;

namespace SLRCTech.PublicDisplays
{

    /// <summary>
    /// Public Displays
    /// </summary>
    public partial interface IPublicDisplays
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event RS-232 Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> RS232Button_PressEvent;

        /// <summary>
        /// RS-232 Button.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void RS232Button_Visibility_fb(bool digital);

        /// <summary>
        /// RS-232 Button.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void RS232Button_Visibility_fb(PublicDisplaysBoolInputSigDelegate callback);

        /// <summary>
        /// Public Displays.VisibilityJoin Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void VisibilityJoin(bool digital);

        /// <summary>
        /// Public Displays.VisibilityJoin Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void VisibilityJoin(PublicDisplaysBoolInputSigDelegate callback);

        /// <summary>
        /// ComplexComponent Header
        /// </summary>
        SLRCTech.PublicDisplays.IHeader Header { get; }

        /// <summary>
        /// ComplexComponent Page Select Tab Button
        /// </summary>
        SLRCTech.PublicDisplays.IPageSelectTabButton PageSelectTabButton { get; }

        /// <summary>
        /// ComplexComponent PD Routing
        /// </summary>
        SLRCTech.PublicDisplays.IPDRouting PDRouting { get; }

        /// <summary>
        /// ComplexComponent PD Lower Level
        /// </summary>
        SLRCTech.PublicDisplays.PDLowerLevel.IPDLowerLevel PDLowerLevel { get; }

        /// <summary>
        /// ComplexComponent PD 1st Floor
        /// </summary>
        SLRCTech.PublicDisplays.PD1stFloor.IPD1stFloor PD1stFloor { get; }

        /// <summary>
        /// ComplexComponent PD 2nd Floor
        /// </summary>
        SLRCTech.PublicDisplays.PD2ndFloor.IPD2ndFloor PD2ndFloor { get; }

        /// <summary>
        /// ComplexComponent PD 3rd Floor
        /// </summary>
        SLRCTech.PublicDisplays.PD3rdFloor.IPD3rdFloor PD3rdFloor { get; }

        /// <summary>
        /// ComplexComponent Building Mute
        /// </summary>
        SLRCTech.PublicDisplays.IBuildingMute BuildingMute { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="publicdisplays">The <see cref="IPublicDisplays"/> on which to apply the feedback.</param>
    public delegate void PublicDisplaysBoolInputSigDelegate(BoolInputSig boolInputSig, IPublicDisplays publicdisplays);

    /// <summary>
    /// Public Displays
    /// </summary>
    internal partial class PublicDisplays : IPublicDisplays, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: PublicDisplays.RS232Button.Press
                /// RS-232 Button.Press
                /// </summary>
                public const uint RS232Button_PressEvent = 2;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.RS232Button.Visibility_fb
                /// RS-232 Button.Visibility
                /// </summary>
                public const uint RS232Button_Visibility_fbState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplaysVisibilityJoin
                /// Public Displays.VisibilityJoin
                /// </summary>
                public const uint VisibilityJoinState = 2;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicDisplays"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal PublicDisplays(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicDisplays"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal PublicDisplays(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicDisplays"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.RS232Button_PressEvent, onRS232Button_Press);
            Header = new SLRCTech.PublicDisplays.Header(ComponentMediator, 80);
            PageSelectTabButton = new SLRCTech.PublicDisplays.PageSelectTabButton(ComponentMediator, 81);
            PDRouting = new SLRCTech.PublicDisplays.PDRouting(ComponentMediator, 82);
            PDLowerLevel = new SLRCTech.PublicDisplays.PDLowerLevel.PDLowerLevel(ComponentMediator, 83);
            PD1stFloor = new SLRCTech.PublicDisplays.PD1stFloor.PD1stFloor(ComponentMediator, 90);
            PD2ndFloor = new SLRCTech.PublicDisplays.PD2ndFloor.PD2ndFloor(ComponentMediator, 98);
            PD3rdFloor = new SLRCTech.PublicDisplays.PD3rdFloor.PD3rdFloor(ComponentMediator, 102);
            BuildingMute = new SLRCTech.PublicDisplays.BuildingMute(ComponentMediator, 107);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCTech.PublicDisplays.Header)Header).AddDevice(device);

            ((SLRCTech.PublicDisplays.PageSelectTabButton)PageSelectTabButton).AddDevice(device);

            ((SLRCTech.PublicDisplays.PDRouting)PDRouting).AddDevice(device);

            ((SLRCTech.PublicDisplays.PDLowerLevel.PDLowerLevel)PDLowerLevel).AddDevice(device);

            ((SLRCTech.PublicDisplays.PD1stFloor.PD1stFloor)PD1stFloor).AddDevice(device);

            ((SLRCTech.PublicDisplays.PD2ndFloor.PD2ndFloor)PD2ndFloor).AddDevice(device);

            ((SLRCTech.PublicDisplays.PD3rdFloor.PD3rdFloor)PD3rdFloor).AddDevice(device);

            ((SLRCTech.PublicDisplays.BuildingMute)BuildingMute).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

        ((SLRCTech.PublicDisplays.Header)Header).RemoveDevice(device);

        ((SLRCTech.PublicDisplays.PageSelectTabButton)PageSelectTabButton).RemoveDevice(device);

        ((SLRCTech.PublicDisplays.PDRouting)PDRouting).RemoveDevice(device);

        ((SLRCTech.PublicDisplays.PDLowerLevel.PDLowerLevel)PDLowerLevel).RemoveDevice(device);

        ((SLRCTech.PublicDisplays.PD1stFloor.PD1stFloor)PD1stFloor).RemoveDevice(device);

        ((SLRCTech.PublicDisplays.PD2ndFloor.PD2ndFloor)PD2ndFloor).RemoveDevice(device);

        ((SLRCTech.PublicDisplays.PD3rdFloor.PD3rdFloor)PD3rdFloor).RemoveDevice(device);

        ((SLRCTech.PublicDisplays.BuildingMute)BuildingMute).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> RS232Button_PressEvent;
        private void onRS232Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = RS232Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }
        /// <inheritdoc/>
        public void RS232Button_Visibility_fb(PublicDisplaysBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.RS232Button_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void RS232Button_Visibility_fb(bool digital)
        {
            RS232Button_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void VisibilityJoin(PublicDisplaysBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.VisibilityJoinState], this);
            }
        }

        /// <inheritdoc/>
        public void VisibilityJoin(bool digital)
        {
            VisibilityJoin((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent Header
        /// </summary>
        public SLRCTech.PublicDisplays.IHeader Header { get; private set; }

        /// <summary>
        /// ComplexComponent Page Select Tab Button
        /// </summary>
        public SLRCTech.PublicDisplays.IPageSelectTabButton PageSelectTabButton { get; private set; }

        /// <summary>
        /// ComplexComponent PD Routing
        /// </summary>
        public SLRCTech.PublicDisplays.IPDRouting PDRouting { get; private set; }

        /// <summary>
        /// ComplexComponent PD Lower Level
        /// </summary>
        public SLRCTech.PublicDisplays.PDLowerLevel.IPDLowerLevel PDLowerLevel { get; private set; }

        /// <summary>
        /// ComplexComponent PD 1st Floor
        /// </summary>
        public SLRCTech.PublicDisplays.PD1stFloor.IPD1stFloor PD1stFloor { get; private set; }

        /// <summary>
        /// ComplexComponent PD 2nd Floor
        /// </summary>
        public SLRCTech.PublicDisplays.PD2ndFloor.IPD2ndFloor PD2ndFloor { get; private set; }

        /// <summary>
        /// ComplexComponent PD 3rd Floor
        /// </summary>
        public SLRCTech.PublicDisplays.PD3rdFloor.IPD3rdFloor PD3rdFloor { get; private set; }

        /// <summary>
        /// ComplexComponent Building Mute
        /// </summary>
        public SLRCTech.PublicDisplays.IBuildingMute BuildingMute { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "PublicDisplays", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            RS232Button_PressEvent = null;
        }

        #endregion
    }
}
