//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.701.5.0
//     UI Plugin:   1.4301.17.0
//
//     Project:     SLRC-Fieldhouse
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.1
//     Strategy:    ModernWidgetListStrategy
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCFieldhouse;

namespace SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IFloorboxesInnerWidgetListByItem
    {

        /// <summary>
        /// ComplexComponent Floorboxes - Inner Widget List.Item
        /// </summary>
        SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItem Item { get; }
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class FloorboxesInnerWidgetList
    {
        #region CH5 Contract

        /// <summary>
        /// ComplexComponent Floorboxes - Inner Widget List.Item
        /// </summary>
        public SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItem Item { get; private set; }
        #endregion
    }

    /// <summary>
    /// FloorboxesInnerWidgetList
    /// </summary>
    public partial interface IFloorboxesInnerWidgetList : IFloorboxesInnerWidgetListByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// ComplexComponent Floorboxes - Inner Widget List.Items[0]
        /// </summary>
        SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_0_ Items_0_ { get; }

        /// <summary>
        /// ComplexComponent Floorboxes - Inner Widget List.Items[1]
        /// </summary>
        SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_1_ Items_1_ { get; }

        /// <summary>
        /// ComplexComponent Floorboxes - Inner Widget List.Items[2]
        /// </summary>
        SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_2_ Items_2_ { get; }

        /// <summary>
        /// ComplexComponent Floorboxes - Inner Widget List.Items[3]
        /// </summary>
        SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_3_ Items_3_ { get; }

        /// <summary>
        /// ComplexComponent Floorboxes - Inner Widget List.Items[4]
        /// </summary>
        SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_4_ Items_4_ { get; }

        /// <summary>
        /// ComplexComponent Floorboxes - Inner Widget List.Items[5]
        /// </summary>
        SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_5_ Items_5_ { get; }

        /// <summary>
        /// ComplexComponent Floorboxes - Inner Widget List.Items[6]
        /// </summary>
        SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_6_ Items_6_ { get; }

        /// <summary>
        /// ComplexComponent Floorboxes - Inner Widget List.Items[7]
        /// </summary>
        SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_7_ Items_7_ { get; }
    }


    /// <summary>
    /// FloorboxesInnerWidgetList
    /// </summary>
    internal partial class FloorboxesInnerWidgetList : IFloorboxesInnerWidgetList, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="FloorboxesInnerWidgetList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal FloorboxesInnerWidgetList(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FloorboxesInnerWidgetList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal FloorboxesInnerWidgetList(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="FloorboxesInnerWidgetList"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>();
            Items_0_ = new SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_0_(ComponentMediator, 17, 8);
            Item = new SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Item(ComponentMediator, 17, 8);
            Items_1_ = new SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_1_(ComponentMediator, 18, 8);
            Items_2_ = new SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_2_(ComponentMediator, 19, 8);
            Items_3_ = new SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_3_(ComponentMediator, 20, 8);
            Items_4_ = new SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_4_(ComponentMediator, 21, 8);
            Items_5_ = new SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_5_(ComponentMediator, 22, 8);
            Items_6_ = new SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_6_(ComponentMediator, 23, 8);
            Items_7_ = new SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_7_(ComponentMediator, 24, 8);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_0_)Items_0_).AddDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_1_)Items_1_).AddDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_2_)Items_2_).AddDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_3_)Items_3_).AddDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_4_)Items_4_).AddDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_5_)Items_5_).AddDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_6_)Items_6_).AddDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_7_)Items_7_).AddDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Item)Item).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_0_)Items_0_).RemoveDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_1_)Items_1_).RemoveDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_2_)Items_2_).RemoveDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_3_)Items_3_).RemoveDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_4_)Items_4_).RemoveDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_5_)Items_5_).RemoveDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_6_)Items_6_).RemoveDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Items_7_)Items_7_).RemoveDevice(device);

            ((SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.Item)Item).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        public SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_0_ Items_0_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        public SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_1_ Items_1_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        public SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_2_ Items_2_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        public SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_3_ Items_3_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[4]
        /// </summary>
        public SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_4_ Items_4_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[5]
        /// </summary>
        public SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_5_ Items_5_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[6]
        /// </summary>
        public SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_6_ Items_6_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[7]
        /// </summary>
        public SLRCFieldhouse.FieldhouseAudio.FloorboxesInnerWidgetList.IItems_7_ Items_7_ { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "FloorboxesInnerWidgetList", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
