//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.701.5.0
//     UI Plugin:   1.4301.17.0
//
//     Project:     SLRC-Tech
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.1
//     Strategy:    ModernWidgetListStrategy
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCTech;

namespace SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IFirstFloorLevelsByItem
    {

        /// <summary>
        /// ComplexComponent Item
        /// </summary>
        SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.IItem Item { get; }
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class FirstFloorLevels
    {
        #region CH5 Contract

        /// <summary>
        /// ComplexComponent Item
        /// </summary>
        public SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.IItem Item { get; private set; }
        #endregion
    }

    /// <summary>
    /// FirstFloorLevels
    /// </summary>
    public partial interface IFirstFloorLevels : IFirstFloorLevelsByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.IItems_0_ Items_0_ { get; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.IItems_1_ Items_1_ { get; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.IItems_2_ Items_2_ { get; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.IItems_3_ Items_3_ { get; }
    }


    /// <summary>
    /// FirstFloorLevels
    /// </summary>
    internal partial class FirstFloorLevels : IFirstFloorLevels, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="FirstFloorLevels"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal FirstFloorLevels(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FirstFloorLevels"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal FirstFloorLevels(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="FirstFloorLevels"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>();
            Items_0_ = new SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Items_0_(ComponentMediator, 25, 4);
            Item = new SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Item(ComponentMediator, 25, 4);
            Items_1_ = new SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Items_1_(ComponentMediator, 26, 4);
            Items_2_ = new SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Items_2_(ComponentMediator, 27, 4);
            Items_3_ = new SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Items_3_(ComponentMediator, 28, 4);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Items_0_)Items_0_).AddDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Items_1_)Items_1_).AddDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Items_2_)Items_2_).AddDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Items_3_)Items_3_).AddDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Item)Item).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Items_0_)Items_0_).RemoveDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Items_1_)Items_1_).RemoveDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Items_2_)Items_2_).RemoveDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Items_3_)Items_3_).RemoveDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.Item)Item).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        public SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.IItems_0_ Items_0_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        public SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.IItems_1_ Items_1_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        public SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.IItems_2_ Items_2_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        public SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorLevels.IItems_3_ Items_3_ { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "FirstFloorLevels", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
