//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     SLRC-User
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCUser;

namespace SLRCUser.FieldhouseAudio
{

    /// <summary>
    /// Fieldhouse Audio
    /// </summary>
    public partial interface IFieldhouseAudio 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Fieldhouse Audio.VisibilityJoin Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void FieldhouseAudio_VisibilityJoin(FieldhouseAudioBoolInputSigDelegate callback);

        /// <summary>
        /// Fieldhouse Audio.VisibilityJoin Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void FieldhouseAudio_VisibilityJoin(bool digital);

        /// <summary>
        /// Please Wait Popup.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void PleaseWaitPopup_Visibility_fb(FieldhouseAudioBoolInputSigDelegate callback);

        /// <summary>
        /// Please Wait Popup.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void PleaseWaitPopup_Visibility_fb(bool digital);

        /// <summary>
        /// ComplexComponent Fieldhouse-Pool Audio Controls
        /// </summary>
        SLRCUser.FieldhouseAudio.FloorboxesOuterWidgetList.IFloorboxesOuterWidgetList FloorboxesOuterWidgetList { get; }

        /// <summary>
        /// ComplexComponent Fieldhouse-Pool Audio Controls
        /// </summary>
        SLRCUser.FieldhouseAudio.BoothWidgetList.IBoothWidgetList BoothWidgetList { get; }

        /// <summary>
        /// ComplexComponent Header
        /// </summary>
        SLRCUser.FieldhouseAudio.IHeader Header { get; }

        /// <summary>
        /// ComplexComponent Zones Tab Button
        /// </summary>
        SLRCUser.FieldhouseAudio.IZonesTabButton ZonesTabButton { get; }

        /// <summary>
        /// ComplexComponent Fieldhouse-Pool Audio Controls
        /// </summary>
        SLRCUser.FieldhouseAudio.FloorboxesInnerWidgetList.IFloorboxesInnerWidgetList FloorboxesInnerWidgetList { get; }

        /// <summary>
        /// ComplexComponent Speaker Config Tab Button
        /// </summary>
        SLRCUser.FieldhouseAudio.ISpeakerConfigTabButton SpeakerConfigTabButton { get; }

        /// <summary>
        /// ComplexComponent Fieldhouse-Pool Audio Controls
        /// </summary>
        SLRCUser.FieldhouseAudio.WirelessWidgetList.IWirelessWidgetList WirelessWidgetList { get; }

        /// <summary>
        /// ComplexComponent Building Mute
        /// </summary>
        SLRCUser.FieldhouseAudio.IBuildingMute BuildingMute { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="fieldhouseaudio">The <see cref="IFieldhouseAudio"/> on which to apply the feedback.</param>
    public delegate void FieldhouseAudioBoolInputSigDelegate(BoolInputSig boolInputSig, IFieldhouseAudio fieldhouseaudio);

    /// <summary>
    /// Fieldhouse Audio
    /// </summary>
    internal partial class FieldhouseAudio : IFieldhouseAudio, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: FieldhouseAudioVisibilityJoin
                /// Fieldhouse Audio.VisibilityJoin
                /// </summary>
                public const uint FieldhouseAudio_VisibilityJoinState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: FieldhouseAudio.PleaseWaitPopup.Visibility_fb
                /// Please Wait Popup.Visibility
                /// </summary>
                public const uint PleaseWaitPopup_Visibility_fbState = 2;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="FieldhouseAudio"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal FieldhouseAudio(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FieldhouseAudio"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal FieldhouseAudio(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="FieldhouseAudio"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            FloorboxesOuterWidgetList = new SLRCUser.FieldhouseAudio.FloorboxesOuterWidgetList.FloorboxesOuterWidgetList(ComponentMediator, 13);
            BoothWidgetList = new SLRCUser.FieldhouseAudio.BoothWidgetList.BoothWidgetList(ComponentMediator, 19);
            Header = new SLRCUser.FieldhouseAudio.Header(ComponentMediator, 22);
            ZonesTabButton = new SLRCUser.FieldhouseAudio.ZonesTabButton(ComponentMediator, 23);
            FloorboxesInnerWidgetList = new SLRCUser.FieldhouseAudio.FloorboxesInnerWidgetList.FloorboxesInnerWidgetList(ComponentMediator, 25);
            SpeakerConfigTabButton = new SLRCUser.FieldhouseAudio.SpeakerConfigTabButton(ComponentMediator, 34);
            WirelessWidgetList = new SLRCUser.FieldhouseAudio.WirelessWidgetList.WirelessWidgetList(ComponentMediator, 35);
            BuildingMute = new SLRCUser.FieldhouseAudio.BuildingMute(ComponentMediator, 39);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCUser.FieldhouseAudio.FloorboxesOuterWidgetList.FloorboxesOuterWidgetList)FloorboxesOuterWidgetList).AddDevice(device);

            ((SLRCUser.FieldhouseAudio.BoothWidgetList.BoothWidgetList)BoothWidgetList).AddDevice(device);

            ((SLRCUser.FieldhouseAudio.Header)Header).AddDevice(device);

            ((SLRCUser.FieldhouseAudio.ZonesTabButton)ZonesTabButton).AddDevice(device);

            ((SLRCUser.FieldhouseAudio.FloorboxesInnerWidgetList.FloorboxesInnerWidgetList)FloorboxesInnerWidgetList).AddDevice(device);

            ((SLRCUser.FieldhouseAudio.SpeakerConfigTabButton)SpeakerConfigTabButton).AddDevice(device);

            ((SLRCUser.FieldhouseAudio.WirelessWidgetList.WirelessWidgetList)WirelessWidgetList).AddDevice(device);

            ((SLRCUser.FieldhouseAudio.BuildingMute)BuildingMute).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCUser.FieldhouseAudio.FloorboxesOuterWidgetList.FloorboxesOuterWidgetList)FloorboxesOuterWidgetList).RemoveDevice(device);

            ((SLRCUser.FieldhouseAudio.BoothWidgetList.BoothWidgetList)BoothWidgetList).RemoveDevice(device);

            ((SLRCUser.FieldhouseAudio.Header)Header).RemoveDevice(device);

            ((SLRCUser.FieldhouseAudio.ZonesTabButton)ZonesTabButton).RemoveDevice(device);

            ((SLRCUser.FieldhouseAudio.FloorboxesInnerWidgetList.FloorboxesInnerWidgetList)FloorboxesInnerWidgetList).RemoveDevice(device);

            ((SLRCUser.FieldhouseAudio.SpeakerConfigTabButton)SpeakerConfigTabButton).RemoveDevice(device);

            ((SLRCUser.FieldhouseAudio.WirelessWidgetList.WirelessWidgetList)WirelessWidgetList).RemoveDevice(device);

            ((SLRCUser.FieldhouseAudio.BuildingMute)BuildingMute).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public void FieldhouseAudio_VisibilityJoin(FieldhouseAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.FieldhouseAudio_VisibilityJoinState], this);
            }
        }

        /// <inheritdoc/>
        public void FieldhouseAudio_VisibilityJoin(bool digital)
        {
            FieldhouseAudio_VisibilityJoin((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void PleaseWaitPopup_Visibility_fb(FieldhouseAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.PleaseWaitPopup_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void PleaseWaitPopup_Visibility_fb(bool digital)
        {
            PleaseWaitPopup_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent FloorboxesOuterWidgetList
        /// </summary>
        public SLRCUser.FieldhouseAudio.FloorboxesOuterWidgetList.IFloorboxesOuterWidgetList FloorboxesOuterWidgetList { get; private set; }

        /// <summary>
        /// ComplexComponent BoothWidgetList
        /// </summary>
        public SLRCUser.FieldhouseAudio.BoothWidgetList.IBoothWidgetList BoothWidgetList { get; private set; }

        /// <summary>
        /// ComplexComponent Header
        /// </summary>
        public SLRCUser.FieldhouseAudio.IHeader Header { get; private set; }

        /// <summary>
        /// ComplexComponent Zones Tab Button
        /// </summary>
        public SLRCUser.FieldhouseAudio.IZonesTabButton ZonesTabButton { get; private set; }

        /// <summary>
        /// ComplexComponent FloorboxesInnerWidgetList
        /// </summary>
        public SLRCUser.FieldhouseAudio.FloorboxesInnerWidgetList.IFloorboxesInnerWidgetList FloorboxesInnerWidgetList { get; private set; }

        /// <summary>
        /// ComplexComponent Speaker Config Tab Button
        /// </summary>
        public SLRCUser.FieldhouseAudio.ISpeakerConfigTabButton SpeakerConfigTabButton { get; private set; }

        /// <summary>
        /// ComplexComponent WirelessWidgetList
        /// </summary>
        public SLRCUser.FieldhouseAudio.WirelessWidgetList.IWirelessWidgetList WirelessWidgetList { get; private set; }

        /// <summary>
        /// ComplexComponent BuildingMute
        /// </summary>
        public SLRCUser.FieldhouseAudio.IBuildingMute BuildingMute { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "FieldhouseAudio", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
