//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     SLRC-Tech
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCTech;

namespace SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IFirstFloorWidgetListByItem
    {
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class FirstFloorWidgetList
    {
        #region CH5 Contract


        #endregion
    }

    /// <summary>
    /// FirstFloorWidgetList
    /// </summary>
    public partial interface IFirstFloorWidgetList : IFirstFloorWidgetListByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// BackgroundMusic.BackgroundMusicZoneLevels.First Floor Widget List.List Number Of Items Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void FirstFloorWidgetList_Set_Number_Of_Items(FirstFloorWidgetListUShortInputSigDelegate callback);

        /// <summary>
        /// BackgroundMusic.BackgroundMusicZoneLevels.First Floor Widget List.List Number Of Items Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void FirstFloorWidgetList_Set_Number_Of_Items(ushort analog);

        /// <summary>
        /// BackgroundMusic.BackgroundMusicZoneLevels.First Floor Widget List.List Number Of Items Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void FirstFloorWidgetList_Set_Number_Of_Items(short analog);

        /// <summary>
        /// ComplexComponent Zone Controls.Items[{0}]s[0]
        /// </summary>
        SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.IItems_0_ Items_0_ { get; }

        /// <summary>
        /// ComplexComponent Zone Controls.Items[{0}]s[1]
        /// </summary>
        SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.IItems_1_ Items_1_ { get; }

        /// <summary>
        /// ComplexComponent Zone Controls.Items[{0}]s[2]
        /// </summary>
        SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.IItems_2_ Items_2_ { get; }

        /// <summary>
        /// ComplexComponent Zone Controls.Items[{0}]s[3]
        /// </summary>
        SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.IItems_3_ Items_3_ { get; }

        /// <summary>
        /// ComplexComponent Zone Controls.Items[{0}]
        /// </summary>
        SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.IItem Item { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="firstfloorwidgetlist">The <see cref="IFirstFloorWidgetList"/> on which to apply the feedback.</param>
    public delegate void FirstFloorWidgetListUShortInputSigDelegate(UShortInputSig uShortInputSig, IFirstFloorWidgetList firstfloorwidgetlist);

    /// <summary>
    /// FirstFloorWidgetList
    /// </summary>
    internal partial class FirstFloorWidgetList : IFirstFloorWidgetList, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {
                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Set_Number_Of_Items
                /// BackgroundMusic.BackgroundMusicZoneLevels.First Floor Widget List.List Number Of Items
                /// </summary>
                public const uint FirstFloorWidgetList_Set_Number_Of_ItemsState = 2;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="FirstFloorWidgetList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal FirstFloorWidgetList(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FirstFloorWidgetList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal FirstFloorWidgetList(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="FirstFloorWidgetList"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            Items_0_ = new SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items_0_(ComponentMediator, 39, 4);
            Items_1_ = new SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items_1_(ComponentMediator, 40, 4);
            Items_2_ = new SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items_2_(ComponentMediator, 41, 4);
            Items_3_ = new SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items_3_(ComponentMediator, 42, 4);
            Item = new SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Item(ComponentMediator, 39, 4);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items_0_)Items_0_).AddDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items_1_)Items_1_).AddDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items_2_)Items_2_).AddDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items_3_)Items_3_).AddDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Item)Item).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items_0_)Items_0_).RemoveDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items_1_)Items_1_).RemoveDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items_2_)Items_2_).RemoveDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items_3_)Items_3_).RemoveDevice(device);

            ((SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Item)Item).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract


        /// <inheritdoc/>
        public void FirstFloorWidgetList_Set_Number_Of_Items(FirstFloorWidgetListUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.FirstFloorWidgetList_Set_Number_Of_ItemsState], this);
            }
        }

        /// <inheritdoc/>
        public void FirstFloorWidgetList_Set_Number_Of_Items(ushort analog)
        {
            FirstFloorWidgetList_Set_Number_Of_Items((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void FirstFloorWidgetList_Set_Number_Of_Items(short analog)
        {
            FirstFloorWidgetList_Set_Number_Of_Items((sig, component) => sig.ShortValue = analog);
        }

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        public SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.IItems_0_ Items_0_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        public SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.IItems_1_ Items_1_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        public SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.IItems_2_ Items_2_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        public SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.IItems_3_ Items_3_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[{0}]
        /// </summary>
        public SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.IItem Item { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "FirstFloorWidgetList", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
