//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     SLRC-Tech
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCTech;

namespace SLRCTech.BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList
{

    /// <summary>
    /// Items[2]
    /// </summary>
    public partial interface IItems_2_ 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Volume Down Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ZoneVolumeDownButton_PressEvent;

        /// <summary>
        /// Event BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Volume Mute Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ZoneVolumeMuteButton_PressEvent;

        /// <summary>
        /// Event BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Volume Up Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ZoneVolumeUpButton_PressEvent;

        /// <summary>
        /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Volume Mute Button.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ZoneVolumeMuteButton_Selected(Items_2_BoolInputSigDelegate callback);

        /// <summary>
        /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Volume Mute Button.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ZoneVolumeMuteButton_Selected(bool digital);

        /// <summary>
        /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Volume Gauge.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void ZoneVolumeGauge_LowerTouchfb(Items_2_UShortInputSigDelegate callback);

        /// <summary>
        /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Volume Gauge.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void ZoneVolumeGauge_LowerTouchfb(ushort analog);

        /// <summary>
        /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Volume Gauge.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void ZoneVolumeGauge_LowerTouchfb(short analog);

        /// <summary>
        /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Label.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void ZoneLabel_IndirectRichText(Items_2_StringInputSigDelegate callback);

        /// <summary>
        /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Label.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void ZoneLabel_IndirectRichText(string serial);

        /// <summary>
        /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Level.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void ZoneLevel_IndirectRichText(Items_2_StringInputSigDelegate callback);

        /// <summary>
        /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Level.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void ZoneLevel_IndirectRichText(string serial);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="items_2_">The <see cref="IItems_2_"/> on which to apply the feedback.</param>
    public delegate void Items_2_BoolInputSigDelegate(BoolInputSig boolInputSig, IItems_2_ items_2_);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="items_2_">The <see cref="IItems_2_"/> on which to apply the feedback.</param>
    public delegate void Items_2_UShortInputSigDelegate(UShortInputSig uShortInputSig, IItems_2_ items_2_);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="items_2_">The <see cref="IItems_2_"/> on which to apply the feedback.</param>
    public delegate void Items_2_StringInputSigDelegate(StringInputSig stringInputSig, IItems_2_ items_2_);

    /// <summary>
    /// Items[2]
    /// </summary>
    internal partial class Items_2_ : IItems_2_, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].ZoneControlsCONTRACT.ZoneVolumeDownButton.Press
                /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Volume Down Button.Press
                /// </summary>
                public const uint ZoneVolumeDownButton_PressEvent = 1201;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].ZoneControlsCONTRACT.ZoneVolumeMuteButton.Press
                /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Volume Mute Button.Press
                /// </summary>
                public const uint ZoneVolumeMuteButton_PressEvent = 1202;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].ZoneControlsCONTRACT.ZoneVolumeUpButton.Press
                /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Volume Up Button.Press
                /// </summary>
                public const uint ZoneVolumeUpButton_PressEvent = 1203;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].ZoneControlsCONTRACT.ZoneVolumeMuteButton.Selected
                /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Volume Mute Button.Selected
                /// </summary>
                public const uint ZoneVolumeMuteButton_SelectedState = 1201;

            }
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].ZoneControlsCONTRACT.ZoneVolumeGauge.LowerTouchfb
                /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Volume Gauge.Lower Touch fb
                /// </summary>
                public const uint ZoneVolumeGauge_LowerTouchfbState = 1801;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].ZoneControlsCONTRACT.ZoneLabel.IndirectRichText
                /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Label.Indirect Rich Text
                /// </summary>
                public const uint ZoneLabel_IndirectRichTextState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].ZoneControlsCONTRACT.ZoneLevel.IndirectRichText
                /// BackgroundMusic.BackgroundMusicZoneLevels.FirstFloorWidgetList.Items[2].Zone Level.Indirect Rich Text
                /// </summary>
                public const uint ZoneLevel_IndirectRichTextState = 2;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_2_"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal Items_2_(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_2_"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal Items_2_(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_2_"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.ZoneVolumeDownButton_PressEvent, onZoneVolumeDownButton_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.ZoneVolumeMuteButton_PressEvent, onZoneVolumeMuteButton_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.ZoneVolumeUpButton_PressEvent, onZoneVolumeUpButton_Press);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            return new Indexes((ushort)(controlJoinId - ControlJoinId), 0, false);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ZoneVolumeDownButton_PressEvent;
        private void onZoneVolumeDownButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ZoneVolumeDownButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ZoneVolumeMuteButton_PressEvent;
        private void onZoneVolumeMuteButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ZoneVolumeMuteButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ZoneVolumeUpButton_PressEvent;
        private void onZoneVolumeUpButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ZoneVolumeUpButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void ZoneVolumeMuteButton_Selected(Items_2_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ZoneVolumeMuteButton_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void ZoneVolumeMuteButton_Selected(bool digital)
        {
            ZoneVolumeMuteButton_Selected((sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void ZoneVolumeGauge_LowerTouchfb(Items_2_UShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.ZoneVolumeGauge_LowerTouchfbState], this);
            }
        }

        /// <inheritdoc/>
        public void ZoneVolumeGauge_LowerTouchfb(ushort analog)
        {
            ZoneVolumeGauge_LowerTouchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void ZoneVolumeGauge_LowerTouchfb(short analog)
        {
            ZoneVolumeGauge_LowerTouchfb((sig, component) => sig.ShortValue = analog);
        }

        /// <inheritdoc/>
        public void ZoneLabel_IndirectRichText(Items_2_StringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.ZoneLabel_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void ZoneLabel_IndirectRichText(string serial)
        {
            ZoneLabel_IndirectRichText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void ZoneLevel_IndirectRichText(Items_2_StringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.ZoneLevel_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void ZoneLevel_IndirectRichText(string serial)
        {
            ZoneLevel_IndirectRichText((sig, component) => sig.StringValue = serial);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "Items_2_", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            ZoneVolumeDownButton_PressEvent = null;
            ZoneVolumeMuteButton_PressEvent = null;
            ZoneVolumeUpButton_PressEvent = null;
        }

        #endregion
    }
}
