//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     SLRC-Tech
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCTech;

namespace SLRCTech.PublicDisplays.PublicDisplay2ndFloor
{

    /// <summary>
    /// PublicDisplay2ndFloor
    /// </summary>
    public partial interface IPublicDisplay2ndFloor 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Public Display 2nd Floor.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void PublicDisplay2ndFloor_Visibility_fb(PublicDisplay2ndFloorBoolInputSigDelegate callback);

        /// <summary>
        /// Public Display 2nd Floor.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void PublicDisplay2ndFloor_Visibility_fb(bool digital);

        /// <summary>
        /// ComplexComponent Display Controls
        /// </summary>
        SLRCTech.PublicDisplays.PublicDisplay2ndFloor.SecondFloorWidgetList.ISecondFloorWidgetList SecondFloorWidgetList { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="publicdisplay2ndfloor">The <see cref="IPublicDisplay2ndFloor"/> on which to apply the feedback.</param>
    public delegate void PublicDisplay2ndFloorBoolInputSigDelegate(BoolInputSig boolInputSig, IPublicDisplay2ndFloor publicdisplay2ndfloor);

    /// <summary>
    /// PublicDisplay2ndFloor
    /// </summary>
    internal partial class PublicDisplay2ndFloor : IPublicDisplay2ndFloor, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PublicDisplay2ndFloor.Visibility_fb
                /// Public Display 2nd Floor.Visibility
                /// </summary>
                public const uint PublicDisplay2ndFloor_Visibility_fbState = 1;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicDisplay2ndFloor"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal PublicDisplay2ndFloor(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicDisplay2ndFloor"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal PublicDisplay2ndFloor(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicDisplay2ndFloor"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            SecondFloorWidgetList = new SLRCTech.PublicDisplays.PublicDisplay2ndFloor.SecondFloorWidgetList.SecondFloorWidgetList(ComponentMediator, 127);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCTech.PublicDisplays.PublicDisplay2ndFloor.SecondFloorWidgetList.SecondFloorWidgetList)SecondFloorWidgetList).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCTech.PublicDisplays.PublicDisplay2ndFloor.SecondFloorWidgetList.SecondFloorWidgetList)SecondFloorWidgetList).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public void PublicDisplay2ndFloor_Visibility_fb(PublicDisplay2ndFloorBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.PublicDisplay2ndFloor_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void PublicDisplay2ndFloor_Visibility_fb(bool digital)
        {
            PublicDisplay2ndFloor_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent SecondFloorWidgetList
        /// </summary>
        public SLRCTech.PublicDisplays.PublicDisplay2ndFloor.SecondFloorWidgetList.ISecondFloorWidgetList SecondFloorWidgetList { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "PublicDisplay2ndFloor", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
