//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.701.5.0
//     UI Plugin:   1.4301.17.0
//
//     Project:     SLRC-User
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.1
//     Strategy:    ModernWidgetListStrategy
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCUser;

namespace SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IFirstFloorWidgetListByItem
    {

        /// <summary>
        /// Helper First Floor Widget List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Visible(ushort listItemIndex, bool digital);

        /// <summary>
        /// First Floor Widget List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Visible(ushort listItemIndex, FirstFloorWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// ComplexComponent Item
        /// </summary>
        SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItem Item { get; }
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class FirstFloorWidgetList
    {
        #region CH5 Contract

        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, bool digital)
        {
            List_Item_Visible(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, FirstFloorWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.FirstFloorWidgetList_List_Item1_VisibleState + (uint) listItemIndex], this);
            }
        }


        /// <summary>
        /// ComplexComponent Item
        /// </summary>
        public SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItem Item { get; private set; }
        #endregion
    }

    /// <summary>
    /// FirstFloorWidgetList
    /// </summary>
    public partial interface IFirstFloorWidgetList : IFirstFloorWidgetListByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// First Floor Widget List.List Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void FirstFloorWidgetList_List_Visible(bool digital);

        /// <summary>
        /// First Floor Widget List.List Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void FirstFloorWidgetList_List_Visible(FirstFloorWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// First Floor Widget List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void FirstFloorWidgetList_List_Item1_Visible(bool digital);

        /// <summary>
        /// First Floor Widget List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void FirstFloorWidgetList_List_Item1_Visible(FirstFloorWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// First Floor Widget List.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void FirstFloorWidgetList_List_Item2_Visible(bool digital);

        /// <summary>
        /// First Floor Widget List.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void FirstFloorWidgetList_List_Item2_Visible(FirstFloorWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// First Floor Widget List.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void FirstFloorWidgetList_List_Item3_Visible(bool digital);

        /// <summary>
        /// First Floor Widget List.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void FirstFloorWidgetList_List_Item3_Visible(FirstFloorWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// First Floor Widget List.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void FirstFloorWidgetList_List_Item4_Visible(bool digital);

        /// <summary>
        /// First Floor Widget List.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void FirstFloorWidgetList_List_Item4_Visible(FirstFloorWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// First Floor Widget List.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void FirstFloorWidgetList_List_Item5_Visible(bool digital);

        /// <summary>
        /// First Floor Widget List.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void FirstFloorWidgetList_List_Item5_Visible(FirstFloorWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// First Floor Widget List.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void FirstFloorWidgetList_List_Item6_Visible(bool digital);

        /// <summary>
        /// First Floor Widget List.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void FirstFloorWidgetList_List_Item6_Visible(FirstFloorWidgetListBoolInputSigDelegate callback);

        /// <summary>
        /// First Floor Widget List.List Number Of Items Feedback
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        void FirstFloorWidgetList_Set_Number_Of_Items(ushort analog);

        /// <summary>
        /// First Floor Widget List.List Number Of Items Feedback
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        void FirstFloorWidgetList_Set_Number_Of_Items(short analog);

        /// <summary>
        /// First Floor Widget List.List Number Of Items Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void FirstFloorWidgetList_Set_Number_Of_Items(FirstFloorWidgetListUShortInputSigDelegate callback);

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItems_0_ Items_0_ { get; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItems_1_ Items_1_ { get; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItems_2_ Items_2_ { get; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItems_3_ Items_3_ { get; }

        /// <summary>
        /// ComplexComponent Items[4]
        /// </summary>
        SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItems_4_ Items_4_ { get; }

        /// <summary>
        /// ComplexComponent Items[5]
        /// </summary>
        SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItems_5_ Items_5_ { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="firstfloorwidgetlist">The <see cref="IFirstFloorWidgetList"/> on which to apply the feedback.</param>
    public delegate void FirstFloorWidgetListBoolInputSigDelegate(BoolInputSig boolInputSig, IFirstFloorWidgetList firstfloorwidgetlist);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="firstfloorwidgetlist">The <see cref="IFirstFloorWidgetList"/> on which to apply the feedback.</param>
    public delegate void FirstFloorWidgetListUShortInputSigDelegate(UShortInputSig uShortInputSig, IFirstFloorWidgetList firstfloorwidgetlist);

    /// <summary>
    /// FirstFloorWidgetList
    /// </summary>
    internal partial class FirstFloorWidgetList : IFirstFloorWidgetList, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PD1stFloor.FirstFloorWidgetList.List_Visible
                /// First Floor Widget List.List Visibility
                /// </summary>
                public const uint FirstFloorWidgetList_List_VisibleState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PD1stFloor.FirstFloorWidgetList.List_Item1_Visible
                /// First Floor Widget List.List_Item1_Visible
                /// </summary>
                public const uint FirstFloorWidgetList_List_Item1_VisibleState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PD1stFloor.FirstFloorWidgetList.List_Item2_Visible
                /// First Floor Widget List.List_Item2_Visible
                /// </summary>
                public const uint FirstFloorWidgetList_List_Item2_VisibleState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PD1stFloor.FirstFloorWidgetList.List_Item3_Visible
                /// First Floor Widget List.List_Item3_Visible
                /// </summary>
                public const uint FirstFloorWidgetList_List_Item3_VisibleState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PD1stFloor.FirstFloorWidgetList.List_Item4_Visible
                /// First Floor Widget List.List_Item4_Visible
                /// </summary>
                public const uint FirstFloorWidgetList_List_Item4_VisibleState = 5;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PD1stFloor.FirstFloorWidgetList.List_Item5_Visible
                /// First Floor Widget List.List_Item5_Visible
                /// </summary>
                public const uint FirstFloorWidgetList_List_Item5_VisibleState = 6;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: PublicDisplays.PD1stFloor.FirstFloorWidgetList.List_Item6_Visible
                /// First Floor Widget List.List_Item6_Visible
                /// </summary>
                public const uint FirstFloorWidgetList_List_Item6_VisibleState = 7;

            }
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {
                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: PublicDisplays.PD1stFloor.FirstFloorWidgetList.Set_Number_Of_Items
                /// First Floor Widget List.List Number Of Items
                /// </summary>
                public const uint FirstFloorWidgetList_Set_Number_Of_ItemsState = 2;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="FirstFloorWidgetList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal FirstFloorWidgetList(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FirstFloorWidgetList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal FirstFloorWidgetList(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="FirstFloorWidgetList"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>();
            Items_0_ = new SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_0_(ComponentMediator, 87, 6);
            Item = new SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Item(ComponentMediator, 87, 6);
            Items_1_ = new SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_1_(ComponentMediator, 88, 6);
            Items_2_ = new SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_2_(ComponentMediator, 89, 6);
            Items_3_ = new SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_3_(ComponentMediator, 90, 6);
            Items_4_ = new SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_4_(ComponentMediator, 91, 6);
            Items_5_ = new SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_5_(ComponentMediator, 92, 6);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_0_)Items_0_).AddDevice(device);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_1_)Items_1_).AddDevice(device);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_2_)Items_2_).AddDevice(device);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_3_)Items_3_).AddDevice(device);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_4_)Items_4_).AddDevice(device);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_5_)Items_5_).AddDevice(device);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Item)Item).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_0_)Items_0_).RemoveDevice(device);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_1_)Items_1_).RemoveDevice(device);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_2_)Items_2_).RemoveDevice(device);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_3_)Items_3_).RemoveDevice(device);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_4_)Items_4_).RemoveDevice(device);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Items_5_)Items_5_).RemoveDevice(device);

            ((SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.Item)Item).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Item1_Visible(FirstFloorWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.FirstFloorWidgetList_List_Item1_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Item1_Visible(bool digital)
        {
            FirstFloorWidgetList_List_Item1_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Item2_Visible(FirstFloorWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.FirstFloorWidgetList_List_Item2_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Item2_Visible(bool digital)
        {
            FirstFloorWidgetList_List_Item2_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Item3_Visible(FirstFloorWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.FirstFloorWidgetList_List_Item3_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Item3_Visible(bool digital)
        {
            FirstFloorWidgetList_List_Item3_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Item4_Visible(FirstFloorWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.FirstFloorWidgetList_List_Item4_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Item4_Visible(bool digital)
        {
            FirstFloorWidgetList_List_Item4_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Item5_Visible(FirstFloorWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.FirstFloorWidgetList_List_Item5_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Item5_Visible(bool digital)
        {
            FirstFloorWidgetList_List_Item5_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Item6_Visible(FirstFloorWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.FirstFloorWidgetList_List_Item6_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Item6_Visible(bool digital)
        {
            FirstFloorWidgetList_List_Item6_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Visible(FirstFloorWidgetListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.FirstFloorWidgetList_List_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void FirstFloorWidgetList_List_Visible(bool digital)
        {
            FirstFloorWidgetList_List_Visible((sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void FirstFloorWidgetList_Set_Number_Of_Items(FirstFloorWidgetListUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.FirstFloorWidgetList_Set_Number_Of_ItemsState], this);
            }
        }

        /// <inheritdoc/>
        public void FirstFloorWidgetList_Set_Number_Of_Items(ushort analog)
        {
            FirstFloorWidgetList_Set_Number_Of_Items((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void FirstFloorWidgetList_Set_Number_Of_Items(short analog)
        {
            FirstFloorWidgetList_Set_Number_Of_Items((sig, component) => sig.ShortValue = analog);
        }

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        public SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItems_0_ Items_0_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        public SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItems_1_ Items_1_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        public SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItems_2_ Items_2_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        public SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItems_3_ Items_3_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[4]
        /// </summary>
        public SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItems_4_ Items_4_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[5]
        /// </summary>
        public SLRCUser.PublicDisplays.PD1stFloor.FirstFloorWidgetList.IItems_5_ Items_5_ { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "FirstFloorWidgetList", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
