//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     SLRC-User
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using SLRCUser;

namespace SLRCUser.BackgroundMusic
{

    /// <summary>
    /// Background Music
    /// </summary>
    public partial interface IBackgroundMusic 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event Reset Levels Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ResetLevelsButton_PressEvent;

        /// <summary>
        /// Reset Levels Button.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ResetLevelsButton_Visibility_fb(BackgroundMusicBoolInputSigDelegate callback);

        /// <summary>
        /// Reset Levels Button.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ResetLevelsButton_Visibility_fb(bool digital);

        /// <summary>
        /// Background Music.VisibilityJoin Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void BackgroundMusic_VisibilityJoin(BackgroundMusicBoolInputSigDelegate callback);

        /// <summary>
        /// Background Music.VisibilityJoin Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void BackgroundMusic_VisibilityJoin(bool digital);

        /// <summary>
        /// ComplexComponent Page Select Tab Button
        /// </summary>
        SLRCUser.BackgroundMusic.IPageSelectTabButton PageSelectTabButton { get; }

        /// <summary>
        /// ComplexComponent Header
        /// </summary>
        SLRCUser.BackgroundMusic.IHeader Header { get; }

        /// <summary>
        /// ComplexComponent Background Music Audio Routing
        /// </summary>
        SLRCUser.BackgroundMusic.AudioRouting.IAudioRouting AudioRouting { get; }

        /// <summary>
        /// ComplexComponent Background Music Zone Levels
        /// </summary>
        SLRCUser.BackgroundMusic.IBackgroundMusicZoneLevels BackgroundMusicZoneLevels { get; }

        /// <summary>
        /// ComplexComponent Building Mute
        /// </summary>
        SLRCUser.BackgroundMusic.IBuildingMute BuildingMute { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="backgroundmusic">The <see cref="IBackgroundMusic"/> on which to apply the feedback.</param>
    public delegate void BackgroundMusicBoolInputSigDelegate(BoolInputSig boolInputSig, IBackgroundMusic backgroundmusic);

    /// <summary>
    /// Background Music
    /// </summary>
    internal partial class BackgroundMusic : IBackgroundMusic, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: BackgroundMusic.ResetLevelsButton.Press
                /// Reset Levels Button.Press
                /// </summary>
                public const uint ResetLevelsButton_PressEvent = 2;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: BackgroundMusic.ResetLevelsButton.Visibility_fb
                /// Reset Levels Button.Visibility
                /// </summary>
                public const uint ResetLevelsButton_Visibility_fbState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: BackgroundMusicVisibilityJoin
                /// Background Music.VisibilityJoin
                /// </summary>
                public const uint BackgroundMusic_VisibilityJoinState = 2;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="BackgroundMusic"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal BackgroundMusic(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BackgroundMusic"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal BackgroundMusic(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="BackgroundMusic"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.ResetLevelsButton_PressEvent, onResetLevelsButton_Press);
            PageSelectTabButton = new SLRCUser.BackgroundMusic.PageSelectTabButton(ComponentMediator, 41);
            Header = new SLRCUser.BackgroundMusic.Header(ComponentMediator, 42);
            AudioRouting = new SLRCUser.BackgroundMusic.AudioRouting.AudioRouting(ComponentMediator, 44);
            BackgroundMusicZoneLevels = new SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels(ComponentMediator, 46);
            BuildingMute = new SLRCUser.BackgroundMusic.BuildingMute(ComponentMediator, 47);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCUser.BackgroundMusic.PageSelectTabButton)PageSelectTabButton).AddDevice(device);

            ((SLRCUser.BackgroundMusic.Header)Header).AddDevice(device);

            ((SLRCUser.BackgroundMusic.AudioRouting.AudioRouting)AudioRouting).AddDevice(device);

            ((SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels)BackgroundMusicZoneLevels).AddDevice(device);

            ((SLRCUser.BackgroundMusic.BuildingMute)BuildingMute).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((SLRCUser.BackgroundMusic.PageSelectTabButton)PageSelectTabButton).RemoveDevice(device);

            ((SLRCUser.BackgroundMusic.Header)Header).RemoveDevice(device);

            ((SLRCUser.BackgroundMusic.AudioRouting.AudioRouting)AudioRouting).RemoveDevice(device);

            ((SLRCUser.BackgroundMusic.BackgroundMusicZoneLevels)BackgroundMusicZoneLevels).RemoveDevice(device);

            ((SLRCUser.BackgroundMusic.BuildingMute)BuildingMute).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ResetLevelsButton_PressEvent;
        private void onResetLevelsButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ResetLevelsButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void BackgroundMusic_VisibilityJoin(BackgroundMusicBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.BackgroundMusic_VisibilityJoinState], this);
            }
        }

        /// <inheritdoc/>
        public void BackgroundMusic_VisibilityJoin(bool digital)
        {
            BackgroundMusic_VisibilityJoin((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ResetLevelsButton_Visibility_fb(BackgroundMusicBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ResetLevelsButton_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ResetLevelsButton_Visibility_fb(bool digital)
        {
            ResetLevelsButton_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent Page Select Tab Button
        /// </summary>
        public SLRCUser.BackgroundMusic.IPageSelectTabButton PageSelectTabButton { get; private set; }

        /// <summary>
        /// ComplexComponent Header
        /// </summary>
        public SLRCUser.BackgroundMusic.IHeader Header { get; private set; }

        /// <summary>
        /// ComplexComponent AudioRouting
        /// </summary>
        public SLRCUser.BackgroundMusic.AudioRouting.IAudioRouting AudioRouting { get; private set; }

        /// <summary>
        /// ComplexComponent BackgroundMusicZoneLevels
        /// </summary>
        public SLRCUser.BackgroundMusic.IBackgroundMusicZoneLevels BackgroundMusicZoneLevels { get; private set; }

        /// <summary>
        /// ComplexComponent BuildingMute
        /// </summary>
        public SLRCUser.BackgroundMusic.IBuildingMute BuildingMute { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "BackgroundMusic", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            ResetLevelsButton_PressEvent = null;
        }

        #endregion
    }
}
